[phases.setup]
nixPkgs = ["nodejs-18_x", "gcc"]
aptPkgs = ["python3", "python3-pip", "python3-dev"]

[phases.install]
cmds = [
    "pip3 install --break-system-packages -r requirements.txt",
    "cd frontend && npm install"
]

[phases.build]
cmds = [
    "cd frontend && npm run build"
]

[start]
cmd = "cd src && python3 main.py"
