[phases.setup]
nixPkgs = ["nodejs-18_x", "gcc"]
aptPkgs = ["python3", "python3-pip", "python3-dev", "libpq-dev"]

[phases.install]
cmds = [
    "pip3 install --break-system-packages -r requirements.txt",
    "cd frontend && rm -rf node_modules && npm install --legacy-peer-deps"
]

[phases.build]
cmds = [
    "cd frontend && npm run build"
]

[start]
cmd = "cd src && python3 app.py"
